// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oknexztwmsdbpurjbtys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbmV4enR3bXNkYnB1cmpidHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjYzNjUsImV4cCI6MjA1NTIwMjM2NX0.4fA-scLHkiMQyDUndT8jdZpbP81uLWltfoMOox8HT90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);